spring:
  application:
    name: users
  datasource:
    url: jdbc:mysql://localhost:3306/luccars-db
    username: dev
    password: devpass
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # create, create-drop, validate, update
    show-sql: true
    open-in-view: true
