services:
  mysql:
    image: mysql:8
    container_name: luccars-db
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: luccars-db
      MYSQL_USER: dev
      MYSQL_PASSWORD: devpass
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: